version: '3'
services:
  web1:
    build: challenge/
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy
    links:
      - "mysql"
  mysql:
    image: mysql:8.0.32
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=db
      - MYSQL_ROOT_PASSWORD=root
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 30
networks:
  default:
    driver: bridge