version: "1.0"

services:
  socks1:
    image: ghcr.io/shadowsocks/ssserver-rust
    ports:
      - "8388:8388"
    networks:
      - nw1
    command: ["ssserver","-s","0.0.0.0:8388","-m","aes-256-gcm","-k","wehavetwosocksthisisthefirst"]

  socks2:
    image: ghcr.io/shadowsocks/ssserver-rust
    networks:
      - nw1
      - nw2
    command: ["ssserver","-s","0.0.0.0:8388","-m","chacha20-ietf-poly1305","-k","youareevenreachthegiftforyou"]

  web:
    image: nginx
    volumes:
      - ./web/flag:/usr/share/nginx/html/flag
    networks:
      - nw2

networks:
  nw1:
    driver: bridge
    ipam:
      config:
        - subnet: 100.64.0.0/24
          ip_range: 100.64.0.24/30
  nw2:
    driver: bridge
    ipam:
      config:
        - subnet: 100.64.1.0/24
          ip_range: 100.64.1.24/30
